spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://revolicise.online:3306/big_event
    username: test
    password: _Test141760

mybatis:
  configuration:
    map-underscore-to-camel-case: true  # 驼峰命名规则

uncleyumo:
  privacy-symbol: "**********"